export const OFFERRATESFLY = [
  {
    rate: 'Эконом',
    km: 4,
    baggageFree: 5,
    baggagePrice: 4000,
    baggageMax: 20,
    childAge: 0,
    childSale: 0,
    childSaleIncludeBaggage: false,
  },
  {
    rate: 'Продвинутый',
    km: 8,
    baggageFree: 20,
    baggagePrice: 5000,
    baggageMax: 50,
    childAge: 7,
    childSale: 30,
    childSaleIncludeBaggage: false,
  },
  {
    rate: 'Люкс',
    km: 15,
    baggageFree: 50,
    baggagePrice: 0,
    baggageMax: 50,
    childAge: 16,
    childSale: 30,
    childSaleIncludeBaggage: false,
  },
];
